public final class kotlinx.coroutines.flow.internal.ChildCancelledException extends java.util.concurrent.CancellationException
{

    public void <init>()
    {
        kotlinx.coroutines.flow.internal.ChildCancelledException r0;

        r0 := @this: kotlinx.coroutines.flow.internal.ChildCancelledException;

        specialinvoke r0.<java.util.concurrent.CancellationException: void <init>(java.lang.String)>("Child of the scoped flow was cancelled");

        return;
    }

    public java.lang.Throwable fillInStackTrace()
    {
        kotlinx.coroutines.flow.internal.ChildCancelledException r0;
        boolean $z0;

        r0 := @this: kotlinx.coroutines.flow.internal.ChildCancelledException;

        $z0 = staticinvoke <j.a.z: boolean c()>();

        if $z0 == 0 goto label1;

        specialinvoke r0.<java.util.concurrent.CancellationException: java.lang.Throwable fillInStackTrace()>();

     label1:
        return r0;
    }
}
